export const USER_HISTORY_START = 'USER_HISTORY_START'
export const USER_HISTORY_SUCCESS = 'USER_HISTORY_SUCCESS'
export const USER_HISTORY_FAILED = 'USER_HISTORY_FAILED'

export const INVEST_NOW_APPROVAL_SUCCESS = 'INVEST_NOW_APPROVAL_SUCCESS'
export const INVEST_NOW_START = 'INVEST_NOW_START'
export const INVEST_NOW_SUCCESS = 'INVEST_NOW_SUCCESS'
export const INVEST_NOW_FAILED = 'INVEST_NOW_FAILED'

export const WITHDRAW_NOW_APPROVAL_SUCCESS = 'WITHDRAW_NOW_APPROVAL_SUCCESS'
export const WITHDRAW_NOW_START = 'WITHDRAW_NOW_START'
export const WITHDRAW_NOW_SUCCESS = 'WITHDRAW_NOW_SUCCESS'
export const WITHDRAW_NOW_FAILED = 'WITHDRAW_NOW_FAILED'

export const FUND_ACCOUNT_APPROVAL_SUCCESS = 'FUND_ACCOUNT_APPROVAL_SUCCESS'
export const FUND_ACCOUNT_START = 'FUND_ACCOUNT_START'
export const FUND_ACCOUNT_SUCCESS = 'FUND_ACCOUNT_SUCCESS'
export const FUND_ACCOUNT_FAILED = 'FUND_ACCOUNT_FAILED'
export const GET_FUND_ACCOUNT_SUCCESS = 'GET_FUND_ACCOUNT_SUCCESS'

export const FETCHED_ORDERS_DELETE = 'FETCHED_ORDERS_DELETE'
export const FETCHED_ORDERS_START = 'FETCHED_ORDERS_START'
export const FETCHED_ORDERS_SUCCESS = 'FETCHED_ORDERS_SUCCESS'
export const FETCHED_ORDERS_FAILED = 'FETCHED_ORDERS_FAILED'
export const DELELTE_ALL_ORDERS = 'DELELTE_ALL_ORDERS'

export const AUTH_GETMEMBER = 'AUTH_GETMEMBER'
export const UPDATE_MEMBER_SUCCESS ='UPDATE_MEMBER_SUCCESS'
export const UPDATE_PROFIT_SUCCESS ='UPDATE_PROFIT_SUCCESS'

export const AUTH_GETUSER = 'AUTH_GETUSER'
export const AUTH_REDIRECT = 'AUTH_REDIRECT'
export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'  
export const AUTH_FAILED = 'AUTH_FAILED'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_CLEAR_ERROR = 'AUTH_CLEAR_ERROR'

export const UPDATE_PROFILE_START ='UPDATE_PROFILE_START'
export const UPDATE_PROFILE_SUCCESS ='UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_FAILED ='UPDATE_PROFILE_FAILED'

export const GET_ADMIN_SUCCESS = 'GET_ADMIN_SUCCESS'
export const GET_USERS_START ='GET_USERS_START'
export const GET_USERS_SUCCESS ='GET_USERS_SUCCESS'
export const GET_USERS_FAILED ='GET_USERS_FAILED'

export const GET_ACTIVITIES = 'GET_ACTIVITIES'


